version: 0.2
env:
  variables:
    LAMBDA_NAME: "test"
phases:
  install:
    runtime-versions:
      java: corretto8

  pre_build:
    commands:
      - echo Test started on `date`  
  build:
    commands:
      - echo Build started on `date`
      - mvn install 
   post build:
    commands:
      - echo Build completed on `date` !!!
      - mvn package
artifacts:
  files:
    - target/amway-tms-enrichment-1.0.0-lambda.jar
  name: vanaraj-$(date +%Y-%m-%d)