version: 0.2
env:
  variables:
    LAMBDA_NAME: "test"
phases:
  install:
    runtime-versions:
      python: 3.7 
    commands:
      - yum install zip
  pre_build:
    commands:
      - pip install virtualenv
      - virtualenv env
      - . env/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
      - ISO_DATE=$(date +%Y-%m-%dT%H:%M:%S%z)
      - TMP_DIR="dist-$ISO_DATE"
      - mkdir $TMP_DIR
      - cp *.py $TMP_DIR
      - cp -rf env/lib/python3.7/site-packages/* $TMP_DIR
      - cd $TMP_DIR
      
artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d)