
version: 0.2
env:
  variables:
    LAMBDA_NAME: "testfunction"
phases:
  install:
    commands:
      - apt-get update
      - apt-get install zip
  pre_build:
    commands:
      - pip install virtualenv
      - virtualenv env
      - . env/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
      - echo Hello from CodeBuild
