version: 0.2
env:
  variables:
    LAMBDA_NAME: "test"
phases:
  install:
    runtime-versions:
      python: 3.7 
    commands:
      - yum install zip
  pre_build:
    commands:
      - pip install virtualenv
      - virtualenv env
      - . env/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
      - echo Hello from CodeBuild