version: 0.2
env:
  variables:
    LAMBDA_NAME: "test"
phases:
  install:
    runtime-versions:
      python: 3.7 
    commands:
      - yum install zip
  pre_build:
    commands:
      - pip install virtualenv
      - virtualenv env
      - . env/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
      - mkdir -p ./package/tmp/
      - cp *.py ./package/tmp/
      - cd ./package/tmp && zip -r ../../$(PROJECT).zip * .[^.]*
      
artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d)