version: 0.2
env:
  variables:
    LAMBDA_NAME: "test"
phases:
  install:
    runtime-versions:
      python: 3.7 
    commands:
      - yum install zip
  pre_build:
    commands:
      - echo Pre Build

  build:
    commands:
      - echo Enter Build Phase
      - mvn install
   post build:
    commands:
      - echo Enter post build phases
      
artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d)