version: 0.2
env:
  variables:
    LAMBDA_NAME: "test"
phases:
  install:
    runtime-versions:
      java: openjdk8
      
  pre_build:
    commands:
      - echo Test started on `date`
      - mvn clean compile test
      
  build:
    commands:
      - echo Build started on `date`
      - mvn package shade:shade
   post build:
    commands:
      - echo Build completed on `date` !!!
artifacts:
  files:
    - '**/*'
  name: vanaraj-$(date +%Y-%m-%d)