version: 0.2
env:
  variables:
    LAMBDA_NAME: "test"
phases:
  install:
    runtime-versions:
      java: corretto8
      
  pre_build:
    commands:
      - echo Pre Build
      
  build:
    commands:
      - echo Build started on `date`
      - mvn test
   post build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d)